# 配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/t_system?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: